[package]
name = "rinet"
version = "1.0.0"
edition = "2021"
authors = ["itsgerliz"]
description = "TCP/IP Client/Server"
license = "MIT"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
tokio = "1.41.0"
